on:
  release:
    types: [published]
jobs:
  trigger-circleci:
    runs-on: ubuntu-latest
    steps:
      - name: circle123
        id: circle123
        uses: circleci/trigger_circleci_pipeline@v1.0
        env:
          CCI_TOKEN: $
